### ISSUE TITLE
migrate to github.com/k3s-io/k3s-ansible

### ISSUE THREAD

**Issue by dweomer** [k3s-io/k3s-ansible#101]
As part of https://github.com/rancher/k3s/issues/2189, @erikwilson and I are responsible for moving the identified repositories over the https://github.com/k3s-io org. I would like to perform the transfer sometime this week (today if I can get a timely response). Short of ensuring the existing outside collaborators have the same permissions post transfer, does anyone have any concerns that this will cause breakage? Keep in mind that git clones and browser navigation will be redirected to the new underlying location transparently.

/cc @itwars @St0rmingBr4in

**Comment by St0rmingBr4in** [comment]
I think we can do the transfer, I don't see any reason it would break.

**Comment by itwars** [comment]
It's good to me too.

**Comment by dweomer** [comment]
This repo has been migrated to the k3s-io org. Please re-open this issue or link to it in a new one to report migration-related problems that you feel need admin attention. Ideally also /cc @dweomer and @erikwilson
