### ISSUE TITLE
Can only get playbook to work with --ask-become-pass

### ISSUE THREAD

**Issue by tylerlittlefield** [k3s-io/k3s-ansible#106]
I've copied my SSH key using:

```bash
ssh-copy-id -i ~/.ssh/id_rsa.pub <user>@<ip>
```

I then attempt to login to the machine with:

```bash
ssh <user>@<ip>
```

And I successfully login, no password needed. However, if I run:

```bash
ansible-playbook site.yml -i inventory/hosts.ini
```

I get:

```bash
PLAY [k3s_cluster] **********************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************
Saturday 12 December 2020  15:23:51 -0800 (0:00:00.019)       0:00:00.019 *****
fatal: [192.168.1.139]: FAILED! => {"msg": "Missing sudo password"}
fatal: [192.168.1.249]: FAILED! => {"msg": "Missing sudo password"}

PLAY RECAP ******************************************************************************************************************************************************************************
192.168.1.139              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
192.168.1.249              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

I can get the playbook to succeed with:

```bash
ansible-playbook site.yml -i inventory/hosts.ini --ask-become-pass
```

Is this okay? Or am I at risk of things not working properly? Any tips or ideas to point me in the right direction would be appreciated!

**Comment by gottsman** [comment]
Hoping you figured this one out by now, but I stumbled upon it.... Look into sudo configuration and NOPASSWD.

**Comment by Matheus-de-Souza** [comment]
@tyluRp You must define your private ssh key to connect to your hosts with ansible. Like this:

`ansible-playbook site.yml -i inventory/hosts.ini --key-file ~/.ssh/id_rsa`

Tip: You can set the variable `ANSIBLE_HOST_KEY_CHECKING=false` to ignore that annoying confirmation to accept not known hosts when you connect for first time to your hosts. If you want to do that, the command will be like this:

`ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook site.yml -i inventory/hosts.ini --key-file ~/.ssh/id_rsa`

**Comment by dtaivpp** [comment]
+1 to what gottsman said. Also look into using visudo to verify changes because its very easy to accidentally mess up the sudoers file which could lock you out of your server.

**Comment by dereknola** [comment]
You need 2 things for this playbook to work by default
1) Passwordless SSH access to all targets
2) Access to root/sudo user on all targets

You can get around this with what is discussed above. 

This has now been highlighted in the readme.
