### ISSUE TITLE
CA Certificate on fresh install

### ISSUE THREAD

**Issue by tylerlittlefield** [k3s-io/k3s-ansible#109]
Fair warning, zero experience incoming!

I have a cluster of raspberry pi's I'm playing with. I have a static site hosted with NGINX on one of the nodes with a valid certificate. When I run the playbook as shown in the README, I noticed a "ExampleCorp" boilerplate certificate that causes my NGINX site to die. I can revive the site once I remove k3s with the reset role.

Does any of this sound familiar to those with more experience? Any ideas or pointers would be greatly appreciated!

**Comment by nullset2** [comment]
Seconding this, it'd be cool if more details were provided, to replace this with a self-signed certificate.
