### ISSUE TITLE
Agent and server on same node : same host/port used, bind address already in use

### ISSUE THREAD

**Issue by goacid** [k3s-io/k3s-ansible#122]
Hi

When setting node and server on same node it never works.
Agent and Node bind on same localhost address and same port.
Is it something normal or just I misunderstand something for this case regarding inventories ?

inventories:
```
[master]
192.168.1.1

[node]
192.168.1.1

[k3s_cluster:children]
master
node

```

Error message : 
`  4070 server.go:159] listen tcp 0.0.0.0:10250: bind: address already in use`

I try to fix --bind-address on server and agent.
Worked on server but not on agent, no such parameters.
So first service launch own the ports, and the other stay dead.

**Comment by St0rmingBr4in** [comment]
K3s masters also have kubelet running by default so I guess you just need to define it as master and not as node as well.
