### ISSUE TITLE
Add support for embedded DB HA mode

### ISSUE THREAD

**Issue by kopwei** [k3s-io/k3s-ansible#127]
Since v1.19.5, K3s added support for HA mode with embedded ETCD and I hope this could be supported in Ansible scripts.

The document is described at [K3s HA Embedded mode](https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/)

Generally. First we shall define "K3S_TOKEN" as an input value, the value should be a string **without special chars**. e.g. "mySecret123", 
- On first master node, k3s should start via command "K3S_TOKEN='mySeceret123' k3s server --cluster-init [--extra server config]"
- On other master, k3s should start via command "K3S_TOKEN='mySecret123' k3s server --server=https://<IP_OF_1st_MASTER>:6443 [--extra server config]"
- For the rest worker nodes, k3s shall start as k3s-agent as before

**Comment by 212850a** [comment]
It's already implemented in this repo - https://github.com/k3s-io/k3s-ansible/tree/k3s-ha ;)

**Comment by 2fst4u** [comment]
It's also in this issue https://github.com/k3s-io/k3s-ansible/issues/32

**Comment by dtaivpp** [comment]
> will these changes be merged into master?

Curious about this as well. Seems to automatically detect if there are multiple masters so I don't see why it couldn't be added back in.
