### ISSUE TITLE
Script uses old k3s version by default

### ISSUE THREAD

**Issue by RobertFloor** [k3s-io/k3s-ansible#129]
By default, the playbooks use an old version of k3s 
---k3s_version: v1.17.5+k3s1

The newest versions is v1.21.1+k3s1 

Maybe this can be updated?

**Comment by JaccoVeldscholten** [comment]
You should be able to create pull request with modification of the file:
https://github.com/k3s-io/k3s-ansible/blob/master/inventory/sample/group_vars/all.yml
k3s_version: v1.17.5+k3s1 -> v1.21.1+k3s1

**Comment by mikev1963** [comment]
You can modify that here:  inventory/my-cluster/group_vars/all.yml

---
k3s_version: v1.21.2+k3s1
ansible_user: mikev1963
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""

**Comment by Coolp** [comment]
Hi All,

New Pull Request created: https://github.com/k3s-io/k3s-ansible/pull/150

Regards,
Pavel

**Comment by alexksg** [comment]
@Coolp looks like your PR is merged 👍 is there a way to upgrade existing cluster to the latest version ?
