### ISSUE TITLE
Only seeing master, No nodes

### ISSUE THREAD

**Issue by anthonybudd** [k3s-io/k3s-ansible#135]
I ran this playbook on 3x Pi 3's. The install seems to be successful however when I run `kubectl get nodes`
 I only see the master node, there are no other worker nodes?

```sh
> ansible-playbook site.yml -i inventory/pi-cluster/hosts.ini

> scp pi@192.168.1.64:~/.kube/config ~/.kube/config

> kubectl get nodes
NAME          STATUS   ROLES    AGE   VERSION
raspberrypi   Ready    master    1h   v1.17.5+k3s1
```

Does anyone have any suggestions about how I can get the other 2 nodes talking to the master?

**Possibile Issue?**
When I run `nmap 192.168.1.0/24` I've noticed that the master node doesn't have port [6443](https://github.com/k3s-io/k3s-ansible/blob/master/roles/k3s/node/templates/k3s.service.j2#L10) open? Is this preventing the nodes for communicating to kuber on the master node?
```sh
> nmap 192.168.1.0/24

Nmap scan report for raspberrypi (192.168.1.64) 👈 Master Node
Host is up (0.0030s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE
22/tcp open  ssh 👈 Should port 6443 be listed here to?

Nmap scan report for raspberrypi (192.168.1.90)
Host is up (0.0030s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE
22/tcp open  ssh

Nmap scan report for raspberrypi (192.168.1.91)
Host is up (0.0012s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE
22/tcp open  ssh
```

**Comment by JasonCarter80** [comment]
Same behavior here

**Comment by JasonCarter80** [comment]
If I use v1.20.9+k3s1 it works fine, issues seems to be with latest release.

**Comment by JasonCarter80** [comment]
With v1.21.3+k3s1 it seems to get stuck on [k3s/node : Enable and check K3s service], I left it running over night, no change.   
Regardless, master only no nodes.

This morning, I reset the whole thing, updated to last version: v1.20.9+k3s1, which completed the process but still, no nodes.

**Comment by JasonCarter80** [comment]
My problem is with duplicate hostnames, I imaged 4 SDCARDS for my RasPi cluster all with the same name.   Added a hostname task to rename which resolved my issues here.

**Comment by anthonybudd** [comment]
**SOLVED**
Add this to all.yml `extra_agent_args: "--with-node-id node-$(openssl rand -base64 12)"`

I manually ran this command:
`/usr/local/bin/k3s agent --server https://{{ master_ip }}:6443 --token {{ hostvars[groups['master'][0]]['token'] }} {{ extra_agent_args | default("") }}`

And got an error because all of the raspberry pi's have the same hostname.

See this PR for a fix:
[https://github.com/k3s-io/k3s-ansible/pull/136](https://github.com/k3s-io/k3s-ansible/pull/136)

**Comment by frasercchristie** [comment]
I'm still getting this issue even when I try to manually change all.yml to include `extra_agent_args: "--with-node-id node-$(openssl rand -base64 12)"`

The playbook hangs when it reaches the k3s node "Enable and check K3s service" task. The same function runs fine for the master, it just stalls at the nodes. I'm already using IP addresses in the hosts.ini file.

**Comment by alexdresko** [comment]
Make sure you enable legacy IP tables per https://rancher.com/docs/k3s/latest/en/advanced/#enabling-legacy-iptables-on-raspbian-buster
