### ISSUE TITLE
Q: How to disable traefik?

### ISSUE THREAD

**Issue by MehrCurry** [k3s-io/k3s-ansible#139]
Hi, thanks for the nice work. I created a small cluster without any problems.

But k3s has an option to disable traefik. How can it be done with this ansible script?

**Comment by MartyFox** [comment]
In the `group_vars/all.yml` file you can add additional start options like so:
`extra_server_args: "--disable traefik --disable servicelb"`

These options get added to the service file when templated: 
`ExecStart=/usr/local/bin/k3s server {{ extra_server_args | default("") }}`

After applying Ansible
![image](https://user-images.githubusercontent.com/9006614/130301570-acbaab0d-82bb-4459-adb3-aa2c6576ffbd.png)

Final state
![image](https://user-images.githubusercontent.com/9006614/130301577-cbd03aef-30c5-4c8f-a857-8418050e16ee.png)

**Comment by MehrCurry** [comment]
Great. I missed that.
