### ISSUE TITLE
Disabling swap

### ISSUE THREAD

**Issue by ptr-dorjin** [k3s-io/k3s-ansible#147]
Do we also need to disable swap before installing K3s?
I know that swap **MUST** be disabled before running kubelet (https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)
 I can't find that this role disables swap, and I don't see it in the prerequisites, so I'm not sure if I can install K3s with swap enabled.
What am I missing?

**Comment by vasanthaganeshk** [comment]
My cluster runs with swap.

**Comment by St0rmingBr4in** [comment]
swap should be disabled yes. We need to have this be at least specified in the README

**Comment by xamindar** [comment]
> swap should be disabled yes. We need to have this be at least specified in the README

Can you provide info on why swap needs to be disabled? From my reading around it appears k8s, and by extension, k3s should run fine with swap enabled on more recent versions.

**Comment by DonBower** [comment]
> > swap should be disabled yes. We need to have this be at least specified in the README
> 
> Can you provide info on why swap needs to be disabled? From my reading around it appears k8s, and by extension, k3s should run fine with swap enabled on more recent versions.

https://discuss.kubernetes.io/t/swap-off-why-is-it-necessary/6879/3

**Comment by dereknola** [comment]
Added note in README about disabling swap.
