### ISSUE TITLE
k3s_token is undefined?

### ISSUE THREAD

**Issue by ischoll** [k3s-io/k3s-ansible#148]
When running site.yml I am getting this error, site.yml is failing on the main.yml on this task:
```
- name: Init cluster inside the transient k3s-init service
  command:
    cmd: "systemd-run -p RestartSec=2 \
                      -p Restart=on-failure \
                      --unit=k3s-init \
                      k3s server {{ server_init_args }}"
    creates: "{{ systemd_dir }}/k3s.service"
  args:
    warn: false  # The ansible systemd module does not support transient units
  register: {{ server_init_args }}
```
The  occurring for all 3 master instances is: 
`fatal: [10.0.0.153]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'k3s_token' is undefined\n\nThe error appears to be in '...playbooks/k3s-ansible-k3s-ha/roles/k3s/master/tasks/main.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Init cluster inside the transient k3s-init service\n  ^ here\n"}`

So is this command returning 
`k3s_token`
Is the token what should have populated {{ server_init_args }} ?

My hosts.ini

```
[master]
10.0.0.151
10.0.0.152
10.0.0.153

[node]
10.0.0.161
10.0.0.162
10.0.0.163

[k3s_cluster:children]
master
node
```

**Comment by lewisdonofrio** [comment]
I am getting a token issue as well mine seems to be that the token is not defined by  `token` isn't defined on the master host, at a glance it looks like the `k3s/master` role is not run (that's where it's defined for master) so in your output make sure that; 1. the `k3s/master` role is running, and 2. that the set_fact task for `token` is running and has a value set.  Here is what I'm seeing
TASK [k3s/node : Copy K3s service file] *****************************************************************************************
task path: /home/pirate/k3s-ansible/roles/k3s/node/tasks/main.yml:3
Tuesday 05 October 2021  20:55:40 -0400 (0:00:06.683)       0:00:57.184 ******* 
<192.168.29.171> ESTABLISH SSH CONNECTION FOR USER: pirate
<192.168.29.171> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="pirate"' -o ConnectTimeout=10 -o ControlPath=/home/pirate/.ansible/cp/bb4d177247 192.168.29.171 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp `"&& mkdir "` echo $HOME/.ansible/tmp/ansible-tmp-1633481741.0596213-6411-88041971261356 `" && echo ansible-tmp-1633481741.0596213-6411-88041971261356="` echo $HOME/.ansible/tmp/ansible-tmp-1633481741.0596213-6411-88041971261356 `" ) && sleep 0'"'"''
<192.168.29.128> ESTABLISH SSH CONNECTION FOR USER: pirate
<192.168.29.128> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="pirate"' -o ConnectTimeout=10 -o ControlPath=/home/pirate/.ansible/cp/00aa8f8f42 192.168.29.128 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp `"&& mkdir "` echo $HOME/.ansible/tmp/ansible-tmp-1633481741.1917665-6413-250286897156231 `" && echo ansible-tmp-1633481741.1917665-6413-250286897156231="` echo $HOME/.ansible/tmp/ansible-tmp-1633481741.1917665-6413-250286897156231 `" ) && sleep 0'"'"''
<192.168.29.171> (0, b'ansible-tmp-1633481741.0596213-6411-88041971261356=/home/pirate/.ansible/tmp/ansible-tmp-1633481741.0596213-6411-88041971261356\n', b'')
<192.168.29.120> ESTABLISH SSH CONNECTION FOR USER: pirate
<192.168.29.120> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="pirate"' -o ConnectTimeout=10 -o ControlPath=/home/pirate/.ansible/cp/4a582fb02d 192.168.29.120 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp `"&& mkdir "` echo $HOME/.ansible/tmp/ansible-tmp-1633481741.3166904-6415-168767630115700 `" && echo ansible-tmp-1633481741.3166904-6415-168767630115700="` echo $HOME/.ansible/tmp/ansible-tmp-1633481741.3166904-6415-168767630115700 `" ) && sleep 0'"'"''
<192.168.29.128> (0, b'ansible-tmp-1633481741.1917665-6413-250286897156231=/home/pirate/.ansible/tmp/ansible-tmp-1633481741.1917665-6413-250286897156231\n', b'')
<192.168.29.171> ESTABLISH SSH CONNECTION FOR USER: pirate
<192.168.29.171> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="pirate"' -o ConnectTimeout=10 -o ControlPath=/home/pirate/.ansible/cp/bb4d177247 192.168.29.171 '/bin/sh -c '"'"'rm -f -r /home/pirate/.ansible/tmp/ansible-tmp-1633481741.0596213-6411-88041971261356/ > /dev/null 2>&1 && sleep 0'"'"''
<192.168.29.120> (0, b'ansible-tmp-1633481741.3166904-6415-168767630115700=/home/pirate/.ansible/tmp/ansible-tmp-1633481741.3166904-6415-168767630115700\n', b'')
<192.168.29.139> ESTABLISH SSH CONNECTION FOR USER: pirate
<192.168.29.139> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="pirate"' -o ConnectTimeout=10 -o ControlPath=/home/pirate/.ansible/cp/6ce53a9700 192.168.29.139 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp `"&& mkdir "` echo $HOME/.ansible/tmp/ansible-tmp-1633481741.4986715-6417-193894931725518 `" && echo ansible-tmp-1633481741.4986715-6417-193894931725518="` echo $HOME/.ansible/tmp/ansible-tmp-1633481741.4986715-6417-193894931725518 `" ) && sleep 0'"'"''
<192.168.29.171> (0, b'', b'')
<192.168.29.139> (0, b'ansible-tmp-1633481741.4986715-6417-193894931725518=/home/pirate/.ansible/tmp/ansible-tmp-1633481741.4986715-6417-193894931725518\n', b'')
<192.168.29.128> ESTABLISH SSH CONNECTION FOR USER: pirate
<192.168.29.128> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="pirate"' -o ConnectTimeout=10 -o ControlPath=/home/pirate/.ansible/cp/00aa8f8f42 192.168.29.128 '/bin/sh -c '"'"'rm -f -r /home/pirate/.ansible/tmp/ansible-tmp-1633481741.1917665-6413-250286897156231/ > /dev/null 2>&1 && sleep 0'"'"''
<192.168.29.104> ESTABLISH SSH CONNECTION FOR USER: pirate
<192.168.29.104> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="pirate"' -o ConnectTimeout=10 -o ControlPath=/home/pirate/.ansible/cp/d7a408f1d2 192.168.29.104 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp `"&& mkdir "` echo $HOME/.ansible/tmp/ansible-tmp-1633481741.7155776-6420-250922900941200 `" && echo ansible-tmp-1633481741.7155776-6420-250922900941200="` echo $HOME/.ansible/tmp/ansible-tmp-1633481741.7155776-6420-250922900941200 `" ) && sleep 0'"'"''
<192.168.29.120> ESTABLISH SSH CONNECTION FOR USER: pirate
<192.168.29.120> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="pirate"' -o ConnectTimeout=10 -o ControlPath=/home/pirate/.ansible/cp/4a582fb02d 192.168.29.120 '/bin/sh -c '"'"'rm -f -r /home/pirate/.ansible/tmp/ansible-tmp-1633481741.3166904-6415-168767630115700/ > /dev/null 2>&1 && sleep 0'"'"''
<192.168.29.128> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/template/__init__.py", line 1094, in do_template
    res = j2_concat(rf)
  File "<template>", line 18, in root
  File "/usr/lib/python3/dist-packages/jinja2/runtime.py", line 635, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/plugins/action/template.py", line 146, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/template/__init__.py", line 1131, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'
fatal: [192.168.29.171]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'"
}
The full traceback is:
Traceback (most recent call last):
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/template/__init__.py", line 1094, in do_template
    res = j2_concat(rf)
  File "<template>", line 18, in root
  File "/usr/lib/python3/dist-packages/jinja2/runtime.py", line 635, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/plugins/action/template.py", line 146, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/template/__init__.py", line 1131, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'
fatal: [192.168.29.128]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'"
}
<192.168.29.104> (0, b'ansible-tmp-1633481741.7155776-6420-250922900941200=/home/pirate/.ansible/tmp/ansible-tmp-1633481741.7155776-6420-250922900941200\n', b'')
<192.168.29.232> ESTABLISH SSH CONNECTION FOR USER: pirate
<192.168.29.232> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="pirate"' -o ConnectTimeout=10 -o ControlPath=/home/pirate/.ansible/cp/29c1b49ec8 192.168.29.232 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp `"&& mkdir "` echo $HOME/.ansible/tmp/ansible-tmp-1633481741.9139733-6424-255781102190137 `" && echo ansible-tmp-1633481741.9139733-6424-255781102190137="` echo $HOME/.ansible/tmp/ansible-tmp-1633481741.9139733-6424-255781102190137 `" ) && sleep 0'"'"''
<192.168.29.120> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/template/__init__.py", line 1094, in do_template
    res = j2_concat(rf)
  File "<template>", line 18, in root
  File "/usr/lib/python3/dist-packages/jinja2/runtime.py", line 635, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/plugins/action/template.py", line 146, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/template/__init__.py", line 1131, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'
fatal: [192.168.29.120]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'"
}
<192.168.29.139> ESTABLISH SSH CONNECTION FOR USER: pirate
<192.168.29.139> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="pirate"' -o ConnectTimeout=10 -o ControlPath=/home/pirate/.ansible/cp/6ce53a9700 192.168.29.139 '/bin/sh -c '"'"'rm -f -r /home/pirate/.ansible/tmp/ansible-tmp-1633481741.4986715-6417-193894931725518/ > /dev/null 2>&1 && sleep 0'"'"''
<192.168.29.232> (0, b'ansible-tmp-1633481741.9139733-6424-255781102190137=/home/pirate/.ansible/tmp/ansible-tmp-1633481741.9139733-6424-255781102190137\n', b'')
<192.168.29.139> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/template/__init__.py", line 1094, in do_template
    res = j2_concat(rf)
  File "<template>", line 18, in root
  File "/usr/lib/python3/dist-packages/jinja2/runtime.py", line 635, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/plugins/action/template.py", line 146, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/template/__init__.py", line 1131, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'
fatal: [192.168.29.139]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'"
}
<192.168.29.104> ESTABLISH SSH CONNECTION FOR USER: pirate
<192.168.29.104> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="pirate"' -o ConnectTimeout=10 -o ControlPath=/home/pirate/.ansible/cp/d7a408f1d2 192.168.29.104 '/bin/sh -c '"'"'rm -f -r /home/pirate/.ansible/tmp/ansible-tmp-1633481741.7155776-6420-250922900941200/ > /dev/null 2>&1 && sleep 0'"'"''
<192.168.29.104> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/template/__init__.py", line 1094, in do_template
    res = j2_concat(rf)
  File "<template>", line 18, in root
  File "/usr/lib/python3/dist-packages/jinja2/runtime.py", line 635, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/plugins/action/template.py", line 146, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/template/__init__.py", line 1131, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'
fatal: [192.168.29.104]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'"
}
<192.168.29.232> ESTABLISH SSH CONNECTION FOR USER: pirate
<192.168.29.232> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="pirate"' -o ConnectTimeout=10 -o ControlPath=/home/pirate/.ansible/cp/29c1b49ec8 192.168.29.232 '/bin/sh -c '"'"'rm -f -r /home/pirate/.ansible/tmp/ansible-tmp-1633481741.9139733-6424-255781102190137/ > /dev/null 2>&1 && sleep 0'"'"''
<192.168.29.232> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/template/__init__.py", line 1094, in do_template
    res = j2_concat(rf)
  File "<template>", line 18, in root
  File "/usr/lib/python3/dist-packages/jinja2/runtime.py", line 635, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/plugins/action/template.py", line 146, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/home/pirate/.local/lib/python3.7/site-packages/ansible/template/__init__.py", line 1131, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'
fatal: [192.168.29.232]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'token'"
}

PLAY RECAP **********************************************************************************************************************
192.168.29.104             : ok=15   changed=0    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
192.168.29.120             : ok=15   changed=0    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
192.168.29.128             : ok=15   changed=0    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
192.168.29.139             : ok=15   changed=0    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
192.168.29.171             : ok=15   changed=0    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
192.168.29.232             : ok=15   changed=0    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
192.168.29.240             : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

**Comment by lewisdonofrio** [comment]
fwiw I have this setup I have this hardware https://tinyurl.com/donofriovines/photos/tech-2020/turing-pi-adventure

**Comment by spencerrung** [comment]
Just wanted to give a ➕ 1 on this. Not sure why, maybe related to the newer version os raspberry pi os?

**Comment by spencerrung** [comment]
Jk, the issue I had was that the `/k3s-ansible/inventory/my-cluster/group_vars' needs to be in the same path as your `hosts.ini` I forgot to move mine. I am guessing its the folder structure.

**Comment by ischoll** [comment]
@spencerrung Thanks, I'll try this out.
