### ISSUE TITLE
Not able to create cluster with more than 1 master.

### ISSUE THREAD

**Issue by kal4oz** [k3s-io/k3s-ansible#152]
Hi guys,

Looks like when I use the code from master branch, everything is working as a charm! :) 

But I tried to create cluster with 3 masters and 3 workers. The playbook runs successful, but the problem is that 2 of the masters are outside the cluster. 
Then I started checking the repo and found out that there is k3s-ha branch, but the error I'm getting there is:

fatal: [192.168.34.41]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {% if groups['master'] | length > 1 %}\n  {% if ansible_host == hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) %}\n    --cluster-init\n  {% else %}\n    --server https://{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}:6443\n  {% endif %}\n  --token {{ k3s_token }}\n{% endif %} {{ extra_server_args | default('') }}: 'k3s_token' is undefined\n\nThe error appears to be in '/home/mwalletadm/k3s-ansible/roles/k3s/master/tasks/main.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Init cluster inside the transient k3s-init service\n  ^ here\n"}

For all the master servers.

Have someone experienced something similar or do you have a workaround?

**Comment by ischoll** [comment]
See https://github.com/k3s-io/k3s-ansible/issues/148
