### ISSUE TITLE
The reset role does not use k3s_server_location

### ISSUE THREAD

**Issue by jon-stumpf** [k3s-io/k3s-ansible#160]
**k3s_server_location** was introduced in #133 but is only used during the installation (**site.yml** playbook).  The same location should also be used during uninstallation (**reset.yml** playbook).

**Comment by dereknola** [comment]
Resolved with https://github.com/k3s-io/k3s-ansible/commit/cd725780f5a58bb8a51c53ed625501ab3e5af475
