### ISSUE TITLE
pkill in roles/reset/tasks/main.yml assumes the path for the k3s data directory ends with "k3s"

### ISSUE THREAD

**Issue by jon-stumpf** [k3s-io/k3s-ansible#161]
**k3s_server_location** was introduced in #133 and can be used to change the location of the data directory (default: /var/lib/rancher/k3s).  In **roles/reset/tasks/main.yml**, pkill is used to kill k3s processes with a pattern that begins with "k3s/data".  "k3s" is part of what can change with **k3s_server_location**.

If one changes the location and the path does not end with "k3s", the _containerd-shim_ processes will not be killed.

**Comment by dereknola** [comment]
Resolved with https://github.com/k3s-io/k3s-ansible/pull/230
