### ISSUE TITLE
symlink'd commands (kubectl, crictl, and ctr) create copy of k3s state when k3s_server_location is set

### ISSUE THREAD

**Issue by jon-stumpf** [k3s-io/k3s-ansible#162]
Symbolic links (to k3s) for kubectl, crictl, and ctr will create a copy of the k3s state under /var/lib/rancher/k3s (the default) if k3s_server_location is set to some other location.  This leaves an artifact after reset.

A quick fix is to create a symbolic link at /var/lib/rancher/k3s to the alternate location.  Alternatively, instead of creating symbolic links, a shell script can be used, calling 'k3s --data-dir {{ k3s_server_location }} "${0##*/}" "${@}"'.

**Comment by dereknola** [comment]
this may no longer be relevant as `reset.yml` now uses the `k3s-uninstall.sh` script for cleanup.

**Comment by dereknola** [comment]
Closing this as we now create a symlink for `/var/lib/rancher/k3s` https://github.com/k3s-io/k3s-ansible/pull/233
