### ISSUE TITLE
Not working with k3s v1.23.*

### ISSUE THREAD

**Issue by daiginjo** [k3s-io/k3s-ansible#168]
If changed the inventory all.yml with the newest k3s version v1.23.1+k3s2, the playbook does not work. Any ideas why / does the framework need a fix?

**Comment by jon-stumpf** [comment]
What error are you seeing?

I do not have an issue running my latest version of **k3s-ansible** which incorporates a number of fixes and pull requests not yet accepted into this repository.  You can try it out here, https://github.com/jon-stumpf/k3s-ansible/tree/master.

**Comment by daiginjo** [comment]
There was an error in the syslog I haven't seen before opening the issue. This was the cause that the control-plane has not started correct and the playbook finished early.

_msg="/var/lib/rancher/k3s/server/cred/passwd newer than datastore and could cause a cluster outage. Remove the file(s) from disk and restart to be recreated from datastore."_

After removing the file the issue was gone.
