### ISSUE TITLE
Undefined variable "k3s_version" executing the playbook

### ISSUE THREAD

**Issue by pierpa71** [k3s-io/k3s-ansible#178]
fatal: [192.168.1.98]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'k3s_version' is undefined\n\nThe error appears to be in '/Users/pierpaolo.bellillo/ansible/playbooks/k3s-ansible/roles/download/tasks/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Download k3s binary x64\n  ^ here\n"}

**Comment by ryancomia** [comment]
i have this same problem
OS version
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

**Comment by ryancomia** [comment]
update: the errors are coming from undefined variables on the defaults/main.yml 
and the download/main.yml 
just followed the tracks and hardcoded. it worked for me.

now another issue is im getting permission denied. its for another issue topic

**Comment by apigban** [comment]
got the same issue, k3s version needs to go [here](https://github.com/k3s-io/k3s-ansible/blob/master/roles/download/tasks/main.yml#:~:text=k3s%20binary%20x64-,get_url,-%3A)

and variable declaration goes [here](https://github.com/k3s-io/k3s-ansible/blob/master/inventory/sample/group_vars/all.yml#:~:text=%2D%2D%2D-,k3s_version,-%3A%20v1.22.3%2Bk3s1) (group_vars)

**Comment by ozbillwang** [comment]
If you follow the document, run below command, and set host file to `inventory/my-cluster/hosts.ini`, you shouldn't see this error. 

This ticket could be closed.

```
cp -R inventory/sample inventory/my-cluster
```

**Comment by beauwest** [comment]
I get that copying the inventory will solve this, however, I'm running my playbooks through Ansible Semaphore, so it means copying things like this are tricky. Just my 2 cents.

**Comment by dereknola** [comment]
Closing this as the repo structure has  drastically changed. I don't have experience with Ansible Semaphore, so let me know/ open a new issue if you can't get it working now.

**Comment by notAunty** [comment]
Still getting the following error message:
`fatal: [192.168.0.1]: FAILED! => {"msg": "The field 'environment' has an invalid value, which includes an undefined variable. The error was: 'k3s_version' is undefined\n\nThe error appears to be in '/home/user/code/turing-pi/k3s-ansible/roles/k3s_server/tasks/main.yml': line 29, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Download K3s binary\n      ^ here\n"}`

I did `cp inventory-sample.yml inventory.yml` as per the README and I used `ansible-playbook playbooks/site.yml -i inventory.yml`
