### ISSUE TITLE
Issue on Rasbian x64 

### ISSUE THREAD

**Issue by jfbourner** [k3s-io/k3s-ansible#179]
When installing on the x64 Rasbian lite I got the below errors 

FAILED! => {"changed": false, "msg": "Unable to start service k3s-node: Job for k3s-node.service failed because the control process exited with error code.\nSee \"systemctl status k3s-node.service\" and \"journalctl -xe\" for details.\n"}

Mar 10 12:47:57 master-node k3s[11411]: time="2022-03-10T12:47:57Z" level=info msg="Run: k3s kubectl"
Mar 10 12:47:57 master-node k3s[11411]: time="2022-03-10T12:47:57Z" level=fatal msg="failed to find memory cgroup (v2)"
Mar 10 12:47:57 master-node systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE

I used this to resolve the issue. (Caveat that I have no idea what it does, but it resolved the issue for me) 
https://github.com/k3s-io/k3s/issues/1825#issuecomment-766322321

**Comment by IanTeda** [comment]
Experiencing the same error

**Comment by JohanNicander** [comment]
> I have the same issue even after adding the cgroup_memory=1 cgroup_enable=memory to /boot/cmdline.txt.

For me enabling cgroups and then rebooting did the trick.

**Comment by jpconstantineau** [comment]
Although the playbook does have the code to be able to set cgroup support (see [here](https://github.com/k3s-io/k3s-ansible/blob/master/roles/raspberrypi/tasks/prereq/Raspbian.yml#L5)), it doesn't get triggered.

I suspect the way the playbook detects Rasbian doesn't correctly pick up the latest 64 bit release and as such, does not run the necessary tasks.

**Comment by dpedersen13** [comment]
enabling cgroups and then rebooting did the trick for me as well

**Comment by JohanNicander** [comment]
I just want to add that a fix for this is in the works here: PR #185

**Comment by fr4nkR** [comment]
having the same issue :(

**Comment by nouknouk** [comment]
FYI,

Same issue here, with RPI4 and raspbian lite ARM64.

- ansible_facts.lsb.id="Debian"
- ansible_facts.lsb.description="Debian GNU/Linux 11 (bullseye)"

shouldn't we add Debian as an eligible lsb.id ?

```
- name: Set detected_distribution to Raspbian
  set_fact:
    detected_distribution: Raspbian
  when: >
    raspberry_pi|default(false) and
    ( ansible_facts.lsb.id|default("") == "Raspbian" or
      ansible_facts.lsb.id|default("") == "Debian" or
      ansible_facts.lsb.description|default("") is match("[Rr]aspbian.*") )
```

**Comment by KI7ODK** [comment]
> I just want to add that a fix for this is in the works here: PR #185

Yep. I used this fix the other day deploying to the latest version of Raspberry Pi OS, and it worked.

**Comment by romelBen** [comment]
I'm having the same issue with Raspbian Bullseye 64bit with the same error `level=fatal msg="failed to find memory cgroup (v2)"`. Even with the `cgroup_memory=1 cgroup_enable=memory` added, I'm still receiving this error when setting up k3s. 

I hope a fix will be had soon.

**Comment by dereknola** [comment]
https://github.com/k3s-io/k3s-ansible/pull/151 has now been merged and iptables and cgroups issues around PI should now be resolved. Feel free to reopen if issue still exists.
