### ISSUE TITLE
Where to add an installation option in installation file of k3s?

### ISSUE THREAD

**Issue by Epic55** [k3s-io/k3s-ansible#182]
Hi, i can't get access to k3s on aws ec2 via kubectl. It gives me error: Unable to connect to the server: x509: certificate is valid for 10.43.0.1, 127.0.0.1, not [remote ip]. I found how to solve it. I need to add INSTALL_K3S_EXEC="--tls-san [EXTERNAL IP]" option when installing k3s.
Where can i add this option in installation config of k3s?
For example, if i install k3s with curl i do like that: 
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san [EXTERNAL IP]" sh -s -

**Comment by alborotogarcia** [comment]
@Epic55 in server args here: https://github.com/k3s-io/k3s-ansible/blob/8e7081243b4ffa83beffe53b58458824a00d1a38/inventory/sample/group_vars/all.yml#L6
