### ISSUE TITLE
add support for rocky

### ISSUE THREAD

**Issue by Jeter-work** [k3s-io/k3s-ansible#183]
I'm trying to use the playbook to install k3s on the RPi image for Rocky 8.5.  This is available through Rocky's webpage, but I do not know if it is supported by the main project.

I ran `ln -s tasks/prereq/Centos.yml tasks/prereq/Rocky.yml` and this allowed the playbook to proceed past `TASK [raspberrypi : Enable cgroup via boot commandline if not already enabled for Centos]`.  Prior to this change, I received an error because cgroups support was not configured.

I still have not made it through to the end of the playbook without an error.

**Comment by Prividen** [comment]
AlmaLinux also has a similar issues, a few RH-specific tasks just skipping.

I think it is required to change lines in `roles/prereq/tasks/main.yml`,

from:
`when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']` 
to:
`when: ansible_os_family == 'RedHat'`
