### ISSUE TITLE
modify - TASK [k3s/master : Replace https://localhost:6443 by https://master-ip:6443] 

### ISSUE THREAD

**Issue by Jeter-work** [k3s-io/k3s-ansible#184]
TASK [k3s/master : Replace https://localhost:6443 by https://master-ip:6443] 

Expected result:  the task should run

Actual result:

````
TASK [k3s/master : Replace https://localhost:6443 by https://master-ip:6443] *******************************************************************************************************************************************************************************************************************************************

Friday 08 April 2022  03:12:12 -0500 (0:00:00.985)       0:00:48.626 ********** 

fatal: [192.168.86.230]: FAILED! => {"changed": true, "cmd": "k3s kubectl config set-cluster default --server=https://192.168.86.230:6443 --kubeconfig /home/pico/.kube/config", "msg": "[Errno 2] No such file or directory: b'k3s': b'k3s'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
````

Fix: (tested on rocky linux, raspberry pi, arm64 cluster)
use absolute path for command:

command: /usr/local/bin/k3s kubectl config set-cluster default --server=https://{{ master_ip }}:6443 --kubeconfig ~{{ ansible_user }}/.kube/config

Result:

````
TASK [k3s/master : Replace https://localhost:6443 by https://master-ip:6443] *******************************************************************************************************************************************************************************************************************************************

Friday 08 April 2022  03:17:40 -0500 (0:00:01.566)       0:00:48.492 ********** 

changed: [192.168.86.230]

````

If k3s installation location is different per OS, the path may need to be parameterized.  I think this is an ansible or ansible against rocky issue, probably related to environment being loaded before the play is executed, and the play modifies the environment.  Regardless, that change made that task succeed for Rocky.

**Comment by mreimbold** [comment]
I ran into the same situation. The underlying problem is that the root user does not have `/usr/local/bin` (the location of the k3s executable) in his PATH. You can therefore also add `/usr/local/bin` to the PATH as a workaround in an preceding task. 

This could look like this, for example:
```yaml
- name: Add /usr/local/bin to PATH
  hosts: all
  become: true
  tasks:
    - ansible.builtin.copy:
        dest: /etc/environment
        content: 'PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
```

**Comment by dereknola** [comment]
And I broke it again :upside_down_face:

**Comment by dereknola** [comment]
Fixed again.
