### ISSUE TITLE
How to proceed for Version Upgrades or adding nodes

### ISSUE THREAD

**Issue by noesberger** [k3s-io/k3s-ansible#186]
Hello

What is the process for upgrading the kubernetes version? Do I just have to change the version in group_vars and then run the playbook again or is this not supported with the current playbook.

Can I extend an installed cluster with more nodes. Do I just have to add more nodes to the inventory and then run the playbook again?

Thanks for your help.

**Comment by aslanpour** [comment]
I just replaced the version number in group_vars and ran the playbook again to upgrade and it works perfectly.

**Comment by mvhirsch** [comment]
> In my case, ansible also returned a message that is shown below.

The error you're facing is already described in #188. 

----

As for the upgrade: I think updating the variable and re-run the playbook is fine for now (see also https://github.com/k3s-io/k3s-ansible/issues/94#issuecomment-715667638). Please keep in mind, that any upgrade may break you system. Also check keep in mind that any bugfixes done in scripts should be mirrored on your system, too. For a safe upgrade path I suggest:

1. [Drain your node(s)](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/)
2. Upgrade your nodes using k3s-ansible, restart them afterwards
3. Drain your master(s) and upgrade them too, restart them afterwards
4. make sure everything is up and running

**Comment by RodriMora** [comment]
How about addint new nodes? just editing the host.ini file and adding new masters, or nodes works?

**Comment by Kybeer** [comment]
> I just replaced the version number in group_vars and ran the playbook again to upgrade and it works perfectly.
> 
> I had to restart nodes to receive the effect."Destination /usr/local/bin/k3s is not writable", "owner": "root", "secontext": "system_u:object_r:bin_t:s0", "size": 53239808,
> 
> In my case, ansible also returned a message that is shown below.
> 
> ![ansible](https://user-images.githubusercontent.com/11733137/176320003-988234f9-7590-48cf-b249-f236c8b1f6fc.png)

I did the same thing - changed K3s version in group_vars/all.yml - but when I re-run the Playbook I get this error on all my nodes: 

`"Destination /usr/local/bin/k3s is not writable", "owner": "root", "secontext": "system_u:object_r:bin_t:s0", "size": 53239808,`

**Comment by tstackhouse** [comment]
I did this, and jumped right to the latest 1.25 from 1.22.  And that resulted in a lot of weirdness that I'm trying to triage over in https://github.com/k3s-io/k3s/issues/6314.  Don't do that.

**Comment by MalteMagnussen** [comment]
I'd also like to know how to upgrade a k3s installed with this Ansible code. 

Should be a section in the README describing how to do this imo

**Comment by dereknola** [comment]
Now Supported via playbook.
