### ISSUE TITLE
Playbook Doesn't install k3s-killall script

### ISSUE THREAD

**Issue by Setheck** [k3s-io/k3s-ansible#190]
Running this playbook to install k3s doesn't seem to install anything but k3s binary. 
This makes it unclear how to perform a clean restart as the documentation mentions the k3s-killall script -> https://rancher.com/docs/k3s/latest/en/upgrades/killall/

But the script is missing.
This makes me wonder if there any other scripts missing and if this playbook would gracefully handle a version upgrade.

**Comment by gnuninu** [comment]
Sorry i rushed i confused killall with uninstall :) I guess for that a new playbook is needed to handle upgrades...
