### ISSUE TITLE
single node cluster

### ISSUE THREAD

**Issue by dberardo-com** [k3s-io/k3s-ansible#200]
is it possible to create a single node cluster using this playbook?

is so should there be only one mater host or should that host belong both to master and node?

**Comment by pajikos** [comment]
Hi, check #156

**Comment by dberardo-com** [comment]
thanks, that answers it, i think there is one flag that k3s accepts to disable workloads when starting, but i cannot remember which is the one: https://rancher.com/docs/k3s/latest/en/installation/disable-flags/

i understand that that flag is not the default, so that's all good
