### ISSUE TITLE
Signoff missing on old commit

### ISSUE THREAD

**Issue by jon-stumpf** [k3s-io/k3s-ansible#208]
Who can fix this?
> Commit sha: [29e6acb](https://github.com/k3s-io/k3s-ansible/pull/166/commits/29e6acb7e764cc20729aa19b27366b3f28e53ff1), Author: Tomasz Kuzemko, Committer: GitHub; The sign-off is missing.

It creates DCO errors for PRs that include this commit.

**Comment by cwayne18** [comment]
The person pushing the commit would need to push it with -s

**Comment by jon-stumpf** [comment]
@tomasz-kuzemko Can you sign the above commit?

**Comment by dereknola** [comment]
Commit has been squashed and  no longer exists.
