### ISSUE TITLE
Assign static IP addresses to all nodes in a cluster

### ISSUE THREAD

**Issue by harshasrisri** [k3s-io/k3s-ansible#215]
Hi,

I'm a k3s AND ansible noob. I configured only hostnames for all the raspberrypis in my cluster using cloud-init and they were assigned addresses by dhcp. Using only the hostnames, I setup k3s on the cluster using this playbook.

Now, I want to move the cluster into a VLAN, or atleast a separate /24 subnet and want to assign static IP addresses for all nodes in the cluster. How can I`achieve it using this playbook?

**Comment by danielefranceschi** [comment]
If you don't have DHCP with DNS self-registration, fixed IPs can be set in the inventory:
```ini
[master]
mymaster ansible_host=192.168.1.26

[node]
mynode1 ansible_host=192.168.1.34
mynode2 ansible_host=192.168.1.39
mynode3 ansible_host=192.168.1.16

[k3s_cluster:children]
master
node
```
I also suggest to add:
```ini
[all:vars]
ansible_host_key_checking=false
ansible_ssh_extra_args="-o StrictHostKeyChecking=no"
```
/close
