### ISSUE TITLE
Last instruction in README.md didn't make sense

### ISSUE THREAD

**Issue by daugherr** [k3s-io/k3s-ansible#221]
I noted this in the cmemory issue but am logging a separate issue to make sure it's seen. 

The last instruction in README.md didn't make sense to me (scp debian@master_ip:~/.kube/config ~/.kube/config). 

kube.cfg was copied by Ansible to the master node. What didn't make sense to me was the difference between source and target. As written, wouldn't that copy in the same folder? I didn't do that step. Haven't deployed any containers yet but kubectl get nodes sees all my nodes just fine.

I feel like I'm missing something.

**Comment by ninjaoxygen** [comment]
The `scp` command should be run locally on your workstation.

The intent is to copy the kube config from the master node to your local machine, so `kubectl` works from your machine, not just when you are `ssh`ed into the nodes.

**Comment by daugherr** [comment]
Thanks! I do have a Linux laptop so I'll do that there. My primary workstation is still Windows 10. I haven't done much with the Linux subsystem. Will kubectl work from there or is more software needed? I have ssh set up using Powershell and using public/private keys only and a custom port vs. port 22 if that makes any difference. I've set up a config file under ../.ssh for that.

**Comment by ninjaoxygen** [comment]
`scp` and `ssh` are both included in Windows 10. It also works via WSL under Win10/Win11 but that needs different configuration to Windows. I use PuTTY / pscp / plink / Pageant, so I'm not sure how to get the included Windows ones working.
The docs seem to say you can put your private keys at `C:\Users\<username>\.ssh\id_rsa` a.k.a `%USERPROFILE%\.ssh\id_rsa` and it will work.
`kubectl` I have installed from `scoop`, or get it from the official site at  https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/
