### ISSUE TITLE
Issue with hostname / ip in inventory

### ISSUE THREAD

**Issue by garb4ge** [k3s-io/k3s-ansible#246]
I tried to bootstrap a cluster with an inventory that contains an IP for the only server in the inventory. When I started the deployment process, I saw that the server setup was skipped completely whilst the agents were started (of course whilst not being able to contact the master). I found the reason in line https://github.com/k3s-io/k3s-ansible/blob/master/roles/k3s/server/tasks/main.yml#L3 where the hostname is checked against the entry in the inventory. This does not work in case the ip is provided in the inventory? Changing it to
```  when: ansible_all_ipv4_addresses[0] == groups['server'][0]``` 
gives me server, but I see that this is not the ideal solution.

Am I missing a piece here or should the handling be made more robust for the server setup?!

Thanks for the great work!

**Comment by dereknola** [comment]
Just fixed with 3b9982013a6209845f8caf7580b22df947c64903

**Comment by garb4ge** [comment]
Thanks, that was quick!
