### ISSUE TITLE
Add ability to configure k8s components using config files

### ISSUE THREAD

**Issue by zen** [k3s-io/k3s-ansible#279]
In many cases adding config parameters to k8s components like kubelet was deprecated in favour of config files:
https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/

Currently we do not support managing such configurations. I'm mainly interested in kubelet config since it contains critical options like `registryPullQPS` etc.: https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/

I think we would need to:
- add ability to provide kubelet config (either directly or templated)
- copy config file to `/etc/rancher/k3s/` (not sure if that's the best location though. Not clear for me what's the difference to ` /var/lib/rancher/k3s/`)
- detect presence of kubelet config in vars and modify agent and server service file to include `--kubelet-arg=config=/etc/rancher/k3s/kubelet.config`

**Comment by dereknola** [comment]
This is a k3s feature, not at k3s-ansible feature request. I will note that we have already tried going down this road with https://github.com/k3s-io/k3s/issues/2116. The end result is that upstream K8s can't decide if they actually want to deprecate the CLI. There are still flags that ONLY are passed via CLI and we have seen no indication that upstream plans to actually deprecate CLI for any other core components (like api-server etc.)

**Comment by dereknola** [comment]
Also I should not that for your flag in question `registryPullQPS` there is an [associated CLI flag `--registry-qps`](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/). This is the problem, there really aren't that many flags that are exclusive to config, they just renamed a bunch when going from CLI -> config for the kubelet. 

So you can just set `extra-server-args: --kublet-arg="--registry-qps=10"`
