### ISSUE TITLE
Move Raspbian role to prereq

### ISSUE THREAD

**Issue by rockaut** [k3s-io/k3s-ansible#30]
Wouldn't it be better/clearer to move the separate Raspbian role to prereq and just load the taskfile specifically on raspbian? Additional the Raspbian-buster only could also be loaded similarly. WDYT?

**Comment by dereknola** [comment]
Closing as Stale. For what its worth, you not wrong per say. It could be put under prereq. But Raspberry Pi seems to requrire the most setup and has additional task on a Per OS basis. Is basically 
- x86 nodes just need OS specific setup
- Raspberry PIs need 1) Raspbery PI specific setup + 2) OS sepecific setups.

Making PI have a separate role enables additional Prereq sets and keeps it all isolated from the other Architecture.
