### ISSUE TITLE
Airgap  no file was found when using first_found

### ISSUE THREAD

**Issue by Zombiepancake23** [k3s-io/k3s-ansible#325]
Hi,
I'm having this problem where when I run the playbook/site to do the setup it does all the pre req then gets past some of the airgap tasks and then once it gets to distribute it gives me a fatal error and said that there was no files found when using first_found and can be seen in the image bellow (sorry in advanced for the poor quality). I'm not sure what to do as i have followed the readme and have no idea where to start. any assistance would be much apreciated.
![image](https://github.com/k3s-io/k3s-ansible/assets/168148694/69c48ad9-8004-4dc0-a887-4a67d239a364)

**Comment by jtcleek** [comment]
@Zombiepancake23 Check your Ansible version. Per the system requirements you need to be on ansible-core 2.15+. You can execute "ansible --version" to confirm.

**Comment by Zombiepancake23** [comment]
I just checked and it was 2.15 but I have upgraded to 2.16 and am gonna run the playbook again and see if it gets the same issue or any other. Thankyou for the help so far though

**Comment by Zombiepancake23** [comment]
@jtcleek after upgrading to 2.16 its work and hasn't reported a failed, however now there is another issue when it comes to there being no context for k3s-ansible when trying to do the kubectl config

**Comment by jtcleek** [comment]
@Zombiepancake23 What value is set for 'cluster_context' in ./roles/k3s_server/defaults/main.yml

**Comment by Zombiepancake23** [comment]
@jtcleek  it shows that it is set to k3s-ansible
