### ISSUE TITLE
Syntax problem on sysctl with CentOS/RHEL

### ISSUE THREAD

**Issue by wArren-Huang** [k3s-io/k3s-ansible#33]
https://github.com/rancher/k3s-ansible/blob/b508c721ad9de096cc073b8c80bfbaa8ddf6daab/roles/prereq/tasks/main.yml#L35
```
    name: "{{ items }}"
```
should be
```
    name: "{{ item }}"
```

**Comment by mehstg** [comment]
Just hit this issue too

**Comment by jon-stumpf** [comment]
Fixed in commit 01de3488a27bc62443efe731ee57079f64514e8f.  Looks like this can be closed.
