### ISSUE TITLE
Airgap install tasks

### ISSUE THREAD

**Issue by npapapietro** [k3s-io/k3s-ansible#342]
Having issues with airgap install, not sure if it is my lack of understanding but in the task below the agent and server are both installed 
https://github.com/k3s-io/k3s-ansible/blob/91ee70ee17d765df0dd42b0f92a7fbc75193bc63/roles/airgap/tasks/main.yml#L112

I don't think this is the case with the `curl ... | sh -` installer. Because of this I get random issues on restarting the node (use case) where the agent tries to consume the server args such as `flag provided but not defined -write-kubeconfig-mode`

**Comment by dereknola** [comment]
@npapapietro Thanks for finding this. When I wrote the airgap feature, I never tested reboots of the nodes.
