### ISSUE TITLE
Airgap install fails with arm64 architecture

### ISSUE THREAD

**Issue by SimonAuger** [k3s-io/k3s-ansible#365]
Hello,

Thank you for the excellent airgap playbook. Everything is working smoothly except for the "Distribute K3s binary" task in the airgap tasks folder. I had to modify the `src: "{{ airgap_dir }}/k3s" `to `src: "{{ airgap_dir }}/k3s-arm64"` for it to function correctly. While renaming my binary file is an option, I believe it would be more consistent with the image distribution process to detect the architecture first and then distribute the appropriate file. What are your thoughts on this? I'd be happy to work on it and submit a PR if needed.

**Comment by dereknola** [comment]
Thanks for finding this, you are correct, the release names for the binaries are different. However, when installed through the normal install script, the binary k3s-arm64 gets renamed to k3s when moved to the `/usr/local/bin`. I will open a PR to replicate this format.

**Comment by SimonAuger** [comment]
Great ! Thanks for the update
