### ISSUE TITLE
k3s --version : Command not found

### ISSUE THREAD

**Issue by dheurtev** [k3s-io/k3s-ansible#374]
When running the playbooks, I get an error k3s -- version : Command not found
Fix : In your roles source code, the version should be checked as /usr/local/bin/k3s --version instead of k3s --version
My system is Almalinux 9.

/k3s/orchestration/roles/k3s_agent/tasks/main.yml
3c3
<   ansible.builtin.command: k3s --version
---
>   ansible.builtin.command: /usr/local/bin/k3s --version
/k3s/orchestration/roles/k3s_server/tasks/main.yml
3c3
<   ansible.builtin.command: k3s --version
---
>   ansible.builtin.command: /usr/local/bin/k3s --version
246c246
<           k3s kubectl get nodes -l "node-role.kubernetes.io/control-plane=true" -o=jsonpath="{.items[*].metadata.name}"
---
>           /usr/local/bin/k3s kubectl get nodes -l "node-role.kubernetes.io/control-plane=true" -o=jsonpath="{.items[*].metadata.name}"
/k3s/orchestration/roles/k3s_upgrade/tasks/main.yml
5c5
<   ansible.builtin.command: k3s --version
---
>   ansible.builtin.command: /usr/local/bin/k3s --version

**Comment by dereknola** [comment]
We cannot assume that the k3s install location is at `/usr/local/bin/k3s`. Depending on the operations system, the binary may be located else (this is often the case in read only/atomic OSes). The assumption for that line is that K3s will already have been installed on the system, and the PATH will include the location that k3s is in (as should be standard for most programs).


It is expected for that command to fail on instances where K3s has never been installed. Thats why we `ignore_errors: true` for that check.

**Comment by dheurtev** [comment]
Understood, yet in [roles/k3s_upgrade/tasks/main.yml](https://github.com/k3s-io/k3s-ansible/blob/master/roles/k3s_upgrade/tasks/main.yml), ignore_errors:true is not set.
Shouldn't it be added there too ?

**Comment by dereknola** [comment]
Your correct those are both problems with the current repo. I will open a PR to address them.

**Comment by dereknola** [comment]
I just tested with the official [vagrant almalinux 9 box ](https://portal.cloud.hashicorp.com/vagrant/discover/almalinux/9) and I see the PATH as `/home/vagrant/.local/bin:/home/vagrant/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin` which seems pretty standard. K3s is found no problem when installed with the ansible playbook.

**Comment by dheurtev** [comment]
Thank for looking into it. Must be an issue with my system then.
We can consider the first problem closed for now, and I let you remove the unnecessary symlink on the other.
