### ISSUE TITLE
k3s.service - Does not Start

### ISSUE THREAD

**Issue by mikev1963** [k3s-io/k3s-ansible#48]
After a fresh install the playbook ends with the following error:
FAILED. Unable to start service k3s:  Job for k3s.service failed because the control process exited with error code.

Here is the status of the k3s.service:
un 19 15:14:46 master k3s[1087]: E0619 15:14:46.710048    1087 cluster_authentication_trust_controller.go:493] kube-system/extension-apiserver-authentication failed with : context deadline exceeded
Jun 19 15:14:46 master k3s[1087]: E0619 15:14:46.723364    1087 status.go:71] apiserver received an error that is not an metav1.Status: context.deadlineExceededError{}
Jun 19 15:14:46 master k3s[1087]: I0619 15:14:46.724123    1087 trace.go:116] Trace[927478669]: "Create" url:/apis/apiregistration.k8s.io/v1/apiservices,user-agent:k3s/v1.17.5+k3s1 (linux/arm64) kubernetes/
Jun 19 15:14:46 master k3s[1087]: Trace[927478669]: [34.001125181s] [34.000375656s] END
Jun 19 15:14:46 master k3s[1087]: E0619 15:14:46.725191    1087 autoregister_controller.go:194] v2beta1.autoscaling failed with : context deadline exceeded
Jun 19 15:14:46 master k3s[1087]: E0619 15:14:46.780093    1087 status.go:71] apiserver received an error that is not an metav1.Status: context.deadlineExceededError{}
Jun 19 15:14:46 master k3s[1087]: I0619 15:14:46.781135    1087 trace.go:116] Trace[1836866062]: "Create" url:/apis/apiregistration.k8s.io/v1/apiservices,user-agent:k3s/v1.17.5+k3s1 (linux/arm64) kubernetes
Jun 19 15:14:46 master k3s[1087]: Trace[1836866062]: [34.001351143s] [34.000847744s] END
Jun 19 15:14:46 master k3s[1087]: E0619 15:14:46.782577    1087 autoregister_controller.go:194] v2beta2.autoscaling failed with : context deadline exceeded
Jun 19 15:14:55 master k3s[1087]: time="2020-06-19T15:14:55.117854357+01:00" level=error msg="error in txn: context deadline exceeded"

**Comment by fnord123** [comment]
What is the OS distribution, version, and hardware of your target device?  Looks like some sort of 64 bit ARM device but it would be good to know the rest.

Also, is this with a single master node, or also multiple worker nodes, and if so, how many?

**Comment by mikev1963** [comment]
I am running Raspberry PI 4 with 4GB Memory
I am running Raspbian 64-bit Beta
