### ISSUE TITLE
Activating cgroup support error

### ISSUE THREAD

**Issue by Nathan-j-hardee** [k3s-io/k3s-ansible#49]
fatal: [192.168.1.150]: FAILED! => {"msg": "The conditional check 'raspbian is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if raspbian is true %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/james/Downloads/k3s-ansible-master/roles/raspbian/tasks/main.yml': line 10, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Activating cgroup support\n  ^ here\n"}

ansible playbook fails to detect my OS version. 
cat /etc/osrelease:
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"

this is running on an ARM64 system

**Comment by fnord123** [comment]
PR https://github.com/rancher/k3s-ansible/pull/42 fixes this I believe.  Please try that.  Awaiting the PR to be accepted.

**Comment by Nathan-j-hardee** [comment]
Understood, i tested #42 and it fixed the issue with the OS, it did introduce this error however:

fatal: [192.168.1.150]: FAILED! => {"changed": false, "msg": "Destination /boot/firmware/cmdline.txt does not exist !", "rc": 257}

**Comment by fnord123** [comment]
You are correct, that is also reported in issue https://github.com/rancher/k3s-ansible/issues/40.    I'll start a new PR to address this.

**Comment by vincentdyleung** [comment]
Hi, I believe PR #63 introduced a regression and broke this again.
