### ISSUE TITLE
System containers not creating. 

### ISSUE THREAD

**Issue by Nathan-j-hardee** [k3s-io/k3s-ansible#53]
james@dragon:~/Downloads/k3s-ansible-master$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                      READY   STATUS              RESTARTS   AGE
kube-system   helm-install-traefik-xbgdc                0/1     ContainerCreating   0          18m
kube-system   local-path-provisioner-58fb86bdfd-hdddq   0/1     ContainerCreating   0          18m
kube-system   metrics-server-6d684c7b5-xhcq9            0/1     ContainerCreating   0          18m
kube-system   coredns-6c6bb68b64-f99km                  0/1     ContainerCreating   0          18m

 Warning  FailedCreatePodSandBox  47s (x35 over 8m42s)  kubelet, pine1     (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to mount rootfs component &{overlay overlay [workdir=/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/175/work upperdir=/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/175/fs lowerdir=/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1/fs]}: no such device: unknown

i was unable to find a /snapshots/175 and only found a /snapshots/1/

did a reset and re-deploy and have the same issue.

**Comment by dereknola** [comment]
Looks like an issue around acessing the filesystem. Depending on if you're using btrfs or something more complex standard fs mount you may need to look into using the `--snapshotter=btrfs`
