### ISSUE TITLE
"raspbian : Test for Raspbian" runs on centos7 nodes and failed

### ISSUE THREAD

**Issue by admun** [k3s-io/k3s-ansible#62]
encountering an error when trying to create a cluster on centos 7.8.2003 raspberry pi

Saturday 18 July 2020  18:37:32 -0700 (0:01:05.670)       0:01:48.058 ********* 
fatal: [192.168.x.y]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'description'\n\nThe error appears to be in '/home/someone/Codes/k3s-ansible/roles/raspbian/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Test for Raspbian\n  ^ here\n"}

ansible 2.9.10 on Fedora 32, with python 3.8.3

**Comment by admun** [comment]
I think the code should check if description exists:

- name: Test for Raspbian
  set_fact:
    raspbian: '{% if
      ansible_facts.lsb.description is defined and
      ( ansible_facts.architecture is search("arm") and
        ansible_facts.lsb.description is match("[Rr]aspbian.*[Bb]uster") ) or
      ( ansible_facts.architecture is search("aarch64") and
        ansible_facts.lsb.description is match("Debian.*buster") ) %}true{% else %}false{% endif %}'

**Comment by vmorris** [comment]
> I think the code should check if description exists:
> 
>     * name: Test for Raspbian
>       set_fact:
>       raspbian: '{% if
>       ansible_facts.lsb.description is defined and
>       ( ansible_facts.architecture is search("arm") and
>       ansible_facts.lsb.description is match("[Rr]aspbian.*[Bb]uster") ) or
>       ( ansible_facts.architecture is search("aarch64") and
>       ansible_facts.lsb.description is match("Debian.*buster") ) %}true{% else %}false{% endif %}'

This worked for me. I was unable to create a new cluster without the test for description.
