### ISSUE TITLE
Raspberry PI specific settings must only run on a Raspberry PI

### ISSUE THREAD

**Issue by stafwag** [k3s-io/k3s-ansible#68]
Raspberry PI specific settings must only run on a Raspberry PI, not on all arm / arm64 systems. There are other arm systems and arm virtual machines.

**Comment by rubencabrera** [comment]
The related MR says it closes this and other issues, can this one be closed as that is already merged?

**Comment by stafwag** [comment]
Yes.

Thanks for notifying!
