### ISSUE TITLE
-bash error

### ISSUE THREAD

**Issue by kitapplegate** [k3s-io/k3s-ansible#76]
RPi x 4 

Buster 

i have done sudo git clone and have made the my-cluster dir in the inventory. I have changed the host.ini and the all.yml.

I keep getting this. Super new to this stuff and do not know what i have done. thank you for your help. 

-bash: ansible-playbook: command not found

**Comment by stafwag** [comment]
This looks like more like local installation issue.

To use this you'll need to install ansible, so make sure that ansible is installed on the host where you want execute the playbooks from.
