### ISSUE TITLE
[ansible-galaxy]Typo error causing error in Centos execution

### ISSUE THREAD

**Issue by renanqts** [k3s-io/k3s-ansible#77]
I'm facing with this error when I'm using Ansible Galaxy version (in ansible-galaxy branch):

TASK [k3s-ansible/roles/prereq : Set bridge-nf-call-iptables (just to be sure)] ***
fatal: [10.0.10.11]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'items' is undefined\n\nThe error appears to be in '/roles/k3s-ansible/roles/prereq/tasks/main.yml': line 33, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set bridge-nf-call-iptables (just to be sure)\n  ^ here\n"}

That variable should be "item":
https://github.com/rancher/k3s-ansible/blob/f91dfcfc8e2e94d6ff687c3d0ecc7805d38e8517/roles/prereq/tasks/main.yml#L35

**Comment by dereknola** [comment]
Closing as the ansible-galaxy branch has been removed.
