### ISSUE TITLE
How are these roles intended to be installed?

### ISSUE THREAD

**Issue by memelet** [k3s-io/k3s-ansible#84]
Since using the ansible-galaxy method is not supported (even via direct from git) what is the recommend way for using these roles? Just copy and modify?

**Comment by funnym0nk3y** [comment]
I'm struggling with the same issue. Could those roles be made available through galaxy?

**Comment by FilBot3** [comment]
Yes, you're supposed to clone the repository down to your Ansible controller machine. Then make a copy of the inventory folder, and modify that hosts.ini to match your setup. Then run:

```bash
ansible-playbook -i inventory/{your inventory}/hosts.ini site.yml
```

Check these videos out:

* https://www.youtube.com/watch?v=N4bfNefjBSw
