### ISSUE TITLE
raspbian :Activating cgroup support - failure on x64 Debian Buster platform

### ISSUE THREAD

**Issue by ske5074** [k3s-io/k3s-ansible#88]
Getting a 'raspian is true' failed error when master and nodes are x64 Intel Debian Buster , not ARM, not RaspberryPIs

$ ssh 192.168.86.110 uname -a
Linux alfred 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

....
TASK [download : Download k3s binary x64] ******************************************************************************
Sunday 06 September 2020  00:21:32 -0600 (0:00:00.412)       0:00:05.811 ******
changed: [192.168.86.110]
changed: [192.168.86.111]
changed: [192.168.86.112]

TASK [download : Download k3s binary arm64] ****************************************************************************
Sunday 06 September 2020  00:22:13 -0600 (0:00:41.544)       0:00:47.356 ******
skipping: [192.168.86.111]
skipping: [192.168.86.112]
skipping: [192.168.86.110]

TASK [download : Download k3s binary armhf] ****************************************************************************
Sunday 06 September 2020  00:22:13 -0600 (0:00:00.137)       0:00:47.493 ******
skipping: [192.168.86.111]
skipping: [192.168.86.112]
skipping: [192.168.86.110]

TASK [raspbian : Test for Raspbian] ************************************************************************************
Sunday 06 September 2020  00:22:13 -0600 (0:00:00.177)       0:00:47.671 ******
ok: [192.168.86.111]
ok: [192.168.86.112]
ok: [192.168.86.110]
TASK [raspbian : Activating cgroup support] ****************************************************************************
Sunday 06 September 2020  00:22:14 -0600 (0:00:00.299)       0:00:47.970 ******
fatal: [192.168.86.110]: FAILED! => {"msg": "The conditional check 'raspbian is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if raspbian is true %} True {% else %} False {% endif %}\n\nThe error appears to have been in '/home/sean/k3s-ansible/roles/raspbian/tasks/main.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Activating cgroup support\n  ^ here\n"}
fatal: [192.168.86.111]: FAILED! => {"msg": "The conditional check 'raspbian is true' failed. 
...

**Comment by ske5074** [comment]
As a workaround, I removed:
  - role: raspbian
 
Line 9 from site.yml and reran the playbook successfully.  I'm not that strong in ansible but I believe the if statement in the roles/raspbian/tasks/main.yml is incorrectly detecting a RaspberryPi OS for Debian Buster x64

**Comment by mfonner** [comment]
I just experienced this error and fixed it by changing the test case in the raspbian role main.yml file from

```yaml
- name: Activating cgroup support
  when:
    - raspbian is true
```

to

```yaml
- name: Activating cgroup support
  when: raspbian
```

**Comment by dereknola** [comment]
Raspberry Pi OS cgroup support should now be working.
