### ISSUE TITLE
helm-install-traefik pod falls into CrashLoopBackOff state

### ISSUE THREAD

**Issue by krezefal** [k3s-io/k3s-ansible#99]
For quite a long time I faced this problem, but decided to write only now, when I finally got mad. Every few deployments (about every fifth, I didn't let down the exact statistics) a pod with the name `helm-install-traefik`  falls into an `CrashLoopBackOff`  and then `Error` state. Of course, this pod retries to stand again later after pod-restart and sometimes it even can reach the `Complete` state. But almost always, if this happens, `helm-install-traefik` doesn't stand up and the cluster doesn't deploy. The fact, that it can happens every next deploy is very unpleasant.

![helm-traefik-clbo](https://user-images.githubusercontent.com/64612172/99187234-6c2d7d00-2766-11eb-9710-f72ae5a74e8d.png)

This problem was encountered  on **Ubuntu-server 18.04.4 LTS** and **CentOS 7** on x86-64 architecture
Attach describe-pod and logs command output here:

[helm-install-traefik-describe.txt](https://github.com/rancher/k3s-ansible/files/5542430/helm-install-traefik-describe.txt)
[helm-install-traefik-logs.txt](https://github.com/rancher/k3s-ansible/files/5542431/helm-install-traefik-logs.txt)

**Comment by krmao** [comment]
how to fix this ?

even though will done after execute follow code
```
    mv /var/lib/rancher/k3s/server/manifests/traefik.yaml /tmp/traefik.yaml
    kubectl -n kube-system delete helmcharts.helm.cattle.io traefik
    kubectl delete -n kube-system service traefik-dashboard
    kubectl delete -n kube-system ingress traefik-dashboard
    mv /tmp/traefik.yaml /var/lib/rancher/k3s/server/manifests/traefik.yaml
```

but still got the error after restart k3s

```
systemctl restart k3s
```

**Comment by rEVOLution-BlackMamba** [comment]
I got the same issue over here in CentOS 7. Any idea how to solve this??

**Comment by rEVOLution-BlackMamba** [comment]
I solved reinstalling k3s in the node

**Comment by dereknola** [comment]
Make sure firewalls are disabled on the nodes or at least the correct K3s ports are open. https://docs.k3s.io/advanced#red-hat-enterprise-linux--centos--fedora
